--Creacion de areas de trabajo
CREATE USER C##stage IDENTIFIED BY stage123;
CREATE USER C##dw IDENTIFIED BY dw123;
CREATE USER C##produccion IDENTIFIED BY prod123;


GRANT CONNECT, RESOURCE TO C##stage;
GRANT CONNECT, RESOURCE TO C##dw;
GRANT CONNECT, RESOURCE TO C##produccion;


-- AMBIENTE: STAGE
-- Usuario: C##STAGE

CREATE TABLE C##STAGE.BD2_STG_DATOS (
  ANIO NUMBER,
  FECHA DATE,
  HORA VARCHAR2(5),
  RONDA VARCHAR2(50),
  ESTADIO VARCHAR2(100),
  CIUDAD VARCHAR2(100),
  PAIS VARCHAR2(100),
  EQUIPO_LOCAL VARCHAR2(100),
  GOL_LOCAL NUMBER,
  EQUIPO_VISITA VARCHAR2(100),
  GOL_VISITA NUMBER,
  ASISTENCIA NUMBER
);
 


-----------------------------------------------------------
-- AMBIENTE: DATA WAREHOUSE
-- Usuario: C##DW

-- Dimensiones
CREATE TABLE C##DW.BD2_DIM_HORA (
  HORA_KEY NUMBER PRIMARY KEY,
  HORA VARCHAR2(5)
);

CREATE TABLE C##DW.BD2_DIM_SELECCION (
  SELECCION_KEY NUMBER PRIMARY KEY,
  NOMBRE_SELECCION VARCHAR2(100)
);

CREATE TABLE C##DW.BD2_DIM_RONDA (
  RONDA_KEY NUMBER PRIMARY KEY,
  NOMBRE_RONDA VARCHAR2(50)
);

CREATE TABLE C##DW.BD2_DIM_PAIS_ORGANIZADOR (
  PAIS_KEY NUMBER PRIMARY KEY,
  NOMBRE_PAIS_ORGANIZADOR VARCHAR2(100)
);

CREATE TABLE C##DW.BD2_DIM_CIUDAD (
  CIUDAD_KEY NUMBER PRIMARY KEY,
  CIUDAD_ORGANIZADOR VARCHAR2(100),
  PAIS_KEY NUMBER,
  CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY (PAIS_KEY)
    REFERENCES C##DW.BD2_DIM_PAIS_ORGANIZADOR (PAIS_KEY)
);

CREATE TABLE C##DW.BD2_DIM_ESTADIO (
  ESTADIO_KEY NUMBER PRIMARY KEY,
  NOMBRE_ESTADIO VARCHAR2(100),
  CIUDAD_KEY NUMBER,
  CONSTRAINT FK_ESTADIO_CIUDAD FOREIGN KEY (CIUDAD_KEY)
    REFERENCES C##DW.BD2_DIM_CIUDAD (CIUDAD_KEY)
);

-- Tabla de hechos
CREATE TABLE C##DW.BD2_HECHOS (
  ANIO NUMBER,
  FECHA_KEY NUMBER,
  HORA_KEY NUMBER,
  RONDA_KEY NUMBER,
  ESTADIO_KEY NUMBER,
  LOCAL_KEY NUMBER,
  VISITANTE_KEY NUMBER,
  GOL_LOCAL NUMBER,
  GOL_VISITA NUMBER,
  ASISTENCIA NUMBER
);

-- Watermark
CREATE TABLE C##DW.WATERMARK
(
  TABLA VARCHAR2(30),
  PK NUMBER(6,0),
  OPERACION VARCHAR2(1),
  FECHA_INSERT DATE,
  MIGRO VARCHAR2(1) DEFAULT 'N',
  FECHA_OPERADO DATE
);


---------------------------------------------------------
-- AMBIENTE: PRODUCCIÓN
-- Usuario: C##PRODUCCION

CREATE TABLE C##PRODUCCION.BD2_NO_HECHOS (
  ANIO NUMBER,
  FECHA_KEY NUMBER,
  FECHA_COD DATE,
  HORA_KEY NUMBER,
  HORA_COD VARCHAR2(5),
  RONDA_KEY NUMBER,
  NOMBRE_RONDA VARCHAR2(50),
  ESTADIO_KEY NUMBER,
  ESTADIO VARCHAR2(100),
  CIUDAD VARCHAR2(100),
  PAIS VARCHAR2(100),
  LOCAL_KEY NUMBER,
  EQUIPO_LOCAL VARCHAR2(100),
  VISITANTE_KEY NUMBER,
  EQUIPO_VISITA VARCHAR2(100),
  GOL_LOCAL NUMBER,
  GOL_VISITA NUMBER,
  ASISTENCIA NUMBER
);

CREATE TABLE C##PRODUCCION.BD2_CORRELATIVOS (
  DIMENSION VARCHAR2(30),
  VALOR NUMBER(5)
);

CREATE TABLE C##PRODUCCION.BD2_VALORES_DEFAULT (
  CAMPO VARCHAR2(30),
  VALOR NUMBER(38,2)
);

CREATE TABLE C##PRODUCCION.BD2_SEGUIMIENTO (
  DIMENSION VARCHAR2(30),
  USUARIO VARCHAR2(30),
  FECHA DATE
);


------------------------------------------------------
---Permisos Stage
CREATE SYNONYM BD2_STG_DATOS FOR C##STAGE.BD2_STG_DATOS;
GRANT SELECT ON BD2_STG_DATOS TO C##DW;


---Permisos  Dw

CREATE SYNONYM BD2_DIM_HORA FOR C##DW.BD2_DIM_HORA;
CREATE SYNONYM BD2_DIM_SELECCION FOR C##DW.BD2_DIM_SELECCION;
CREATE SYNONYM BD2_DIM_RONDA FOR C##DW.BD2_DIM_RONDA;
CREATE SYNONYM BD2_DIM_PAIS_ORGANIZADOR FOR C##DW.BD2_DIM_PAIS_ORGANIZADOR;
CREATE SYNONYM BD2_DIM_CIUDAD FOR C##DW.BD2_DIM_CIUDAD;
CREATE SYNONYM BD2_DIM_ESTADIO FOR C##DW.BD2_DIM_ESTADIO;
CREATE SYNONYM BD2_HECHOS FOR C##DW.BD2_HECHOS;
CREATE SYNONYM WATERMARK FOR C##DW.WATERMARK;


GRANT SELECT ON BD2_DIM_HORA TO C##PRODUCCION;
GRANT SELECT ON BD2_DIM_SELECCION TO C##PRODUCCION;
GRANT SELECT ON BD2_DIM_RONDA TO C##PRODUCCION;
GRANT SELECT ON BD2_DIM_PAIS_ORGANIZADOR TO C##PRODUCCION;
GRANT SELECT ON BD2_DIM_CIUDAD TO C##PRODUCCION;
GRANT SELECT ON BD2_DIM_ESTADIO TO C##PRODUCCION;
GRANT SELECT ON BD2_HECHOS TO C##PRODUCCION;
GRANT SELECT ON WATERMARK TO C##STAGE;
GRANT SELECT ON WATERMARK TO C##PRODUCCION;

---Permisos producccion
-- Conectado como C##DW

CREATE SYNONYM BD2_NO_HECHOS FOR C##PRODUCCION.BD2_NO_HECHOS;
CREATE SYNONYM BD2_CORRELATIVOS FOR C##PRODUCCION.BD2_CORRELATIVOS;
CREATE SYNONYM BD2_VALORES_DEFAULT FOR C##PRODUCCION.BD2_VALORES_DEFAULT;
CREATE SYNONYM BD2_SEGUIMIENTO FOR C##PRODUCCION.BD2_SEGUIMIENTO;


-- Conectado como C##PRODUCCION
GRANT SELECT ON BD2_NO_HECHOS TO C##DW;
GRANT SELECT ON BD2_CORRELATIVOS TO C##DW;
GRANT SELECT ON BD2_VALORES_DEFAULT TO C##DW;
GRANT SELECT ON BD2_SEGUIMIENTO TO C##DW;

---Triggers para tabla de produccion 

CREATE OR REPLACE TRIGGER C##PRODUCCION.TRG_TABLA_SINC
AFTER INSERT OR UPDATE ON C##PRODUCCION.BD2_NO_HECHOS
FOR EACH ROW
BEGIN
  INSERT INTO C##PRODUCCION.BD2_SEGUIMIENTO (
    DIMENSION,
    USUARIO,
    FECHA
  ) VALUES (
    'BD2_NO_HECHOS',
    USER,
    SYSDATE
  );
END;
--------------------------------

CREATE OR REPLACE PROCEDURE C##STAGE.PRC_SINCRONIZACION AS
BEGIN
  -- Paso 1: Borrar registros anteriores en la tabla Stage
  DELETE FROM C##STAGE.BD2_STG_DATOS;

  -- Paso 2: Insertar nueva información (simulada aquí desde una tabla temporal)
  INSERT INTO C##STAGE.BD2_STG_DATOS (
    ANIO, FECHA, HORA, RONDA, ESTADIO, CIUDAD, PAIS, 
    EQUIPO_LOCAL, GOL_LOCAL, EQUIPO_VISITA, GOL_VISITA, ASISTENCIA
  )
;

  -- Paso 3: Registrar que se hizo una sincronización
  INSERT INTO C##PRODUCCION.BD2_SEGUIMIENTO (
    DIMENSION,
    USUARIO,
    FECHA
  ) VALUES (
    'BD2_STG_DATOS',
    USER,
    SYSDATE
  );
END;

ALTER USER C##STAGE QUOTA UNLIMITED ON USERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##STAGE.BD2_STG_DATOS TO C##DW;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##STAGE.BD2_STG_DATOS TO C##PRODUCCION;

SELECT * FROM "C##STAGE".BD2_STG_DATOS bsd  ;